cask_args appdir: "/Applications"

brew "python@3.14"
brew "python-tk@3.14"
brew "git"
brew "uv"
brew "sqlite"
brew "p7zip"
brew "ripgrep"
brew "mupdf"
brew "poppler"
brew "tesseract"
brew "tesseract-lang"

cask "iterm2"
cask "visual-studio-code"
