cask_args appdir: "/Applications"

brew "python@3.14"
brew "python-tk@3.14"
brew "git"
brew "uv"
brew "sqlite"
brew "p7zip"
brew "ripgrep"
brew "pipx"
brew "node"
brew "cmake"
brew "jq"
brew "bat"
brew "fd"
brew "yq"
brew "ffmpeg"
brew "playwright-cli"
brew "coreutils"
brew "findutils"
brew "gnu-sed"
brew "grep"

cask "iterm2"
cask "visual-studio-code"
cask "jetbrains-toolbox"
